name: Comment on the pull request

on:
  workflow_run:
    workflows: ["Package Neuron for Test"]
    types:
      - completed

jobs:
  comment:
    name: Append links to the Pull Request
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          name: package_info
          run_id: ${{ github.event.workflow_run.id }}

      - id: pr_number
        run: |
          export PR_NUM=$(cat ./pr_number)
          echo "pr_num=$PR_NUM" >> $GITHUB_OUTPUT
      - id: run_id
        run: |
          export RUN_ID=$(cat ./run_id)
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

      - name: Read PR number and job id
        run: |
          echo "${{ steps.pr_number.outputs.pr_num }}"
          echo "${{ steps.run_id.outputs.run_id }}"

      - uses: thollander/actions-comment-pull-request@v2
        if: ${{ steps.pr_number.outputs.pr_num != "" && steps.run_id.outputs.run_id != '' }}
        with:
          message: |
            Packaging for test is done in [${{ steps.run_id.outputs.run_id }}](https://github.com/${{github.repository}}/actions/runs/${{steps.run_id.outputs.run_id}})
          pr_number: steps.pr_number.outputs.pr_num

        

