on: issue_comment
name: Issue Comments
permissions:
  issues: write
  pull-requests: write
jobs:
  check_comments:
    name: Check comments for /test
    runs-on: macos-latest
    env:
      APPLE_ID: ${{ secrets.APPLE_ID }}
    steps:
      - name: Check for Command
        id: command
        uses: xt0rted/slash-command-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command: test
          reaction: "true"
          allow-edits: "true"
          permission-level: write

      - name: Update comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ github.event.comment.id }}
          body: |
            **Edit:** Some additional info
          reactions: eyes

      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Restore
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            */*/node_modules
          key: 2022-12-21-${{ runner.os }}-${{ hashFiles('**/yarn.lock')}}

      - name: Install Lerna
        run: yarn global add lerna

      - name: Boostrap
        run: |
          yarn
        env:
          CI: false

      - name: Package for MacOS
        if: ${{ env.APPLE_ID != '' }}
        run: |
          ./scripts/download-ckb.sh mac
          yarn package:test mac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          CSC_LINK: ${{ secrets.MAC_CERTIFICATE_BASE64 }}
          CSC_KEY_PASSWORD: ${{ secrets.MAC_CERTIFICATE_PASSWORD }}