on: issue_comment
name: Issue Comments
permissions:
  issues: write
  pull-requests: write
jobs:
  check_comments:
    name: Check comments for /test
    runs-on: macos-latest
    env:
      APPLE_ID: ${{ secrets.APPLE_ID }}
    steps:
      - name: Check for Command
        id: command
        uses: xt0rted/slash-command-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command: test
          reaction: "true"
          allow-edits: "true"
          permission-level: write

      - name: Act on the command
        run: echo "The command was '${{ steps.command.outputs.command-name }}' with arguments '${{ steps.command.outputs.command-arguments }}'"

      - name: Update comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ github.event.comment.id }}
          body: |
            **Edit:** Some additional info
          reactions: eyes
          edit-mode: append
