name: Update Neuron compatible

on:
  push:
    branches:
      - 'rc/**'
    paths:
      - 'package.json'

jobs:
  update-neuron-compatible:
    name: Update Neuron compatible
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # open PR
      contents: write # update version files

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Update versions
        id: update_versions
        run: |
          npm run update:neuron-compatible
          git add compatible.json

      - name: Set GPG
        if: ${{ success() }}
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Open PR to RC branch
        if: ${{ success() }}
        uses: peter-evans/create-pull-request@v5
        with:
          title: Update Neuron compatible
          commit-message: 'feat: update Neuron compatible'
          body: 'Update Neuron compatible for a release'
          committer: Chen Yu <chenyu@magickbase.com>
          branch: update-neuron-compatible
          base: ${{ github.ref_name }}