name: Update ckb node assume valid target

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - master

jobs:
  ready-for-release:
    name: Update ckb node assume valid target
    runs-on: ubuntu-latest
    steps:
      - name: Create PR
        uses: technote-space/create-pr-action@v2
        with:
          EXECUTE_COMMANDS: |
            yarn
            yarn update:valid:target
          COMMIT_MESSAGE: 'chore: update ckb node assume valid target'
          COMMIT_NAME: 'GitHub Actions'
          COMMIT_EMAIL: 'neuron@magickbase.com'
          PR_BRANCH_NAME: 'chore-update-${PR_ID}'
          PR_TITLE: 'chore: update ckb node assume valid target'
